#-------------------------------------------------------------------------------
# Laskutin frontend
#-------------------------------------------------------------------------------

FROM node:15.14.0-alpine3.13 as frontend-build-stage

WORKDIR /app

COPY frontend/package*.json ./

RUN npm install

COPY frontend/fonts ./fonts
COPY frontend/public ./public
COPY frontend/src ./src
COPY frontend/tests ./tests
COPY frontend/.browserslistrc frontend/.env frontend/.eslintrc.js frontend/babel.config.js frontend/jest.config.js frontend/vue.config.js ./

RUN npm run build



FROM nginx:1.20.0-alpine

WORKDIR /var/www

COPY --from=frontend-build-stage /app/dist /var/www/dist

COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
