version: "3.4"

services:
    backend:
        container_name: laskutin_backend
        image: laskutin_backend
        build:
            context: .
            dockerfile: Dockerfile-backend
        volumes:
            - type: volume
              source: laskutin_data
              target: /laskutin
        ports:
            - "8001:80"

    frontend:
        container_name: laskutin_frontend
        image: laskutin_frontend
        build:
            context: .
            dockerfile: Dockerfile-frontend
        ports:
            - "8000:80"
        depends_on:
            - backend

volumes:
    laskutin_data:
